$content = Get-Content "src/main/java/in/sih/vaspattribution/engine/AttributionEngine.java" -Raw
$content = $content -replace "public class AttributionEngine \{", "public class AttributionEngine {`n`n    private final java.util.Map<UUID, java.util.List<InvestigationPath>> attributionCache = new java.util.concurrent.ConcurrentHashMap<>();"

$content = $content -replace "(?s)vaspCandidates\.sort\(\(a, b\) -> \{.*?\n                \}\);", "java.util.List<String> addresses = vaspCandidates.stream().map(p -> p.node.getAddress()).collect(java.util.stream.Collectors.toList());`n                java.util.List<in.sih.vaspattribution.entity.entity.EntityAddress> entityAddresses = entityAddressRepository.findAllByAddressIn(addresses);`n                java.util.Map<String, in.sih.vaspattribution.entity.entity.EntityAddress> eaMap = entityAddresses.stream().collect(java.util.stream.Collectors.toMap(in.sih.vaspattribution.entity.entity.EntityAddress::getAddress, e -> e, (e1, e2) -> e1));`n                vaspCandidates.sort((a, b) -> {`n                    int hopCompare = Integer.compare(a.node.getHop(), b.node.getHop());`n                    if (hopCompare != 0) return hopCompare;`n                    in.sih.vaspattribution.entity.entity.EntityAddress eaA = eaMap.get(a.node.getAddress());`n                    in.sih.vaspattribution.entity.entity.EntityAddress eaB = eaMap.get(b.node.getAddress());`n                    int eqA = eaA != null && eaA.getSource() != null ? 1 : 0;`n                    int eqB = eaB != null && eaB.getSource() != null ? 1 : 0;`n                    if (eqA != eqB) return Integer.compare(eqB, eqA);`n                    double confA = eaA != null && eaA.getConfidence() != null ? eaA.getConfidence() : 0.0;`n                    double confB = eaB != null && eaB.getConfidence() != null ? eaB.getConfidence() : 0.0;`n                    if (Double.compare(confA, confB) != 0) return Double.compare(confB, confA);`n                    java.math.BigDecimal amountA = java.math.BigDecimal.ZERO;`n                    if (!a.edges.isEmpty()) {`n                        java.math.BigDecimal val = a.edges.get(a.edges.size() - 1).getAmount();`n                        if (val != null) amountA = val;`n                    }`n                    java.math.BigDecimal amountB = java.math.BigDecimal.ZERO;`n                    if (!b.edges.isEmpty()) {`n                        java.math.BigDecimal val = b.edges.get(b.edges.size() - 1).getAmount();`n                        if (val != null) amountB = val;`n                    }`n                    return amountB.compareTo(amountA);`n                });"

$content = $content -replace "for \(InvestigationPath candidate : vaspCandidates\) \{", "attributionCache.put(investigationId, new java.util.ArrayList<>(vaspCandidates));`n                for (InvestigationPath candidate : vaspCandidates) {"

$content = $content -replace "(?s)public List<InvestigationPath> getAttributionCandidates\(UUID investigationId\) \{.*?return vaspCandidates;`n    \}", "public List<InvestigationPath> getAttributionCandidates(UUID investigationId) {`n        return attributionCache.getOrDefault(investigationId, java.util.Collections.emptyList());`n    }"
Set-Content "src/main/java/in/sih/vaspattribution/engine/AttributionEngine.java" -Value $content
